spring.application.name=ItemStoreAPI

# Consola web para la base de datos H2
# Ruta para acceder a la consola: http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuarcion de la base de datos en memoria H2
spring.datasource.url=jdbc:h2:mwm:itemsDb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=maen
spring.datasource.password=

# Configuracion de JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola
spring.jpa.show-sql=true

# Colores ANSI en la consola
spring.output.ansi.enabled=always