spring.application.name=ItemStoreAPI

# Consola web para la base de datos H2
# Ruta para acceder a la consola: http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuarcion de la base de datos en memoria H2
spring.datasource.url=jdbc:h2:mem:itemsDb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=maen
spring.datasource.password=

# Configuracion de JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create

# Mostrar las consultas SQL en la consola
spring.jpa.show-sql=true

# Colores ANSI en la consola
spring.output.ansi.enabled=always

# Configuracion de OAuth2
spring.security.oauth2.client.registration.github.client-id=Ov23liSQZuanD1mNSsQL
spring.security.oauth2.client.registration.github.client-secret=a87ebca8689d7a43aa03acea3d8e3af65131336f